// Code generated by mockery v2.14.0. DO NOT EDIT.

package note

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: rw, r
func (_m *MockHandler) Create(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

// GetAll provides a mock function with given fields: rw, r
func (_m *MockHandler) GetAll(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

// GetById provides a mock function with given fields: rw, r
func (_m *MockHandler) GetById(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

// Update provides a mock function with given fields: rw, r
func (_m *MockHandler) Update(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

type mockConstructorTestingTNewMockHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHandler(t mockConstructorTestingTNewMockHandler) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
